# Generated by Django 5.1.2 on 2026-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("search", "0005_group_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="group",
            name="members",
        ),
        migrations.RemoveField(
            model_name="message",
            name="group",
        ),
        migrations.RemoveField(
            model_name="message",
            name="sender",
        ),
        migrations.AddField(
            model_name="product",
            name="features",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Call",
        ),
        migrations.DeleteModel(
            name="Group",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
    ]
